on:
  workflow_call:
    inputs:
      fortify_release_id:
        required: true
        type: string
    secrets:
      fortify_password:
        required: true

jobs:
  fortify-sast-scan:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Source Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check Out Pull Request Head
        run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Set Up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Download Fortify ScanCentral Client
        uses: fortify/gha-setup-scancentral-client@v1

      - name: Package Code and Dependencies
        run: scancentral package $PACKAGE_OPTS -o package.zip
        env:
          PACKAGE_OPTS: "-bt none"

      - name: Utilize Fortify on Demand Uploader
        uses: fortify/gha-setup-fod-uploader@v1

      - name: Perform Static Application Security Testing Scan
        run: java -jar $FOD_UPLOAD_JAR -z package.zip -aurl $FOD_API_URL -purl $FOD_URL -rid "$FOD_RELEASE_ID" -tc "$FOD_TENANT" -uc "$FOD_USER" "$FOD_PAT" $FOD_UPLOADER_OPTS -n "$FOD_UPLOADER_NOTES"
        env:
          FOD_TENANT: "nara"
          FOD_USER: "github"
          FOD_PAT: ${{ secrets.fortify_password }}
          FOD_RELEASE_ID: ${{ inputs.fortify_release_id }}
          FOD_URL: "https://ams.fortify.com/"
          FOD_API_URL: "https://api.ams.fortify.com/"
          FOD_UPLOADER_OPTS: "-ep 2 -pp 0 -I 1 -apf"
          FOD_UPLOADER_NOTES: 'Triggered by GitHub Actions (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'

# Optional: Below this line requires GitHub Advanced Security
#      - name: Download Results
#        uses: fortify/gha-fod-generate-sarif@1.1.0
#        with:
#          base-url: https://ams.fortify.com
#          tenant: "nara"
#          user: "github"
#          password: ${{ secrets.fortify_password }}
#          release-id: ${{ inputs.fortify_release_id }}
#          output: ./sarif/output.sarif
#
#      - name: Import Results to GitHub Security Code Scanning
#        uses: github/codeql-action/upload-sarif@v1
#        with:
#          sarif_file: ./sarif/output.sarif
